<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>8.0</LangVersion>
    <Nullable>disable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <Platform>x64</Platform>
    <AssemblyName>ELVZone</AssemblyName>
    <RootNamespace>ELVZone</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ExternalVersion>2022</ExternalVersion>
    <DefineConstants>R2022</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Update="ELVZone.addin">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="EquipmentLibrary\Speakers\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EvaRevitPlugin_$(ExternalVersion)" Version="1.0.0" ExcludeAssets="runtime" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
